#!/bin/bash

# Configure tornado server to allow for running in an iframe:
jupyter notebook --generate-config
echo -e "c.NotebookApp.tornado_settings = {'headers':{'Content-Security-Policy':'frame-ancestors *'}}" >> $HOME/.jupyter/jupyter_notebook_config.py
